import express from 'express';
import { chatController, taskController, getChats, getChatMessages, ingestDocumentController, getUserSummaries, getUserNotes, getUserQuestions } from './ai.controller';
import { requireAuth } from '@clerk/express';
import { rateLimit } from '../../middleware/rateLimit';

const router = express.Router();

/**
 * Chat / Ask AI (Hybrid RAG)
 * POST /api/ai/chat
 */
router.post(
    "/chat",
    requireAuth(),
    rateLimit,
    chatController
);

/**
 * Unified AI Tasks (Questions, Summary, Notes)
 * POST /api/ai/tasks
 */
router.post(
    "/tasks",
    requireAuth(),
    rateLimit,
    taskController
);

/**
 * Chat History
 */
router.get(
    "/chats",
    requireAuth(),
    getChats
);

/**
 * What this API does?
 * => Returns all the chats created by the user
 * GET /api/ai/chats
 */

router.get(
    "/chats/:chatId",
    requireAuth(),
    getChatMessages
);

/**
 * History Routes - User's Generated Content
 */
router.get(
    "/history/summaries",
    requireAuth(),
    getUserSummaries
);

/**
 * What this API does?
 * => Returns all the notes generated by the user
 * GET /api/ai/history/notes
 */

router.get(
    "/history/notes",
    requireAuth(),
    getUserNotes
);

/**
 * What this API does?
 * => Returns all the questions generated by the user
 * GET /api/ai/history/questions
 */

router.get(
    "/history/questions",
    requireAuth(),
    getUserQuestions
);

/**
 * What this API does?
 * => Takes a document content and chunks it into smaller pieces, then stores the embeddings in the database for RAG (Retrieval Augmented Generation)
 * Document Ingestion
 * POST /api/ai/ingest
 */
router.post(
    "/ingest",
    requireAuth(),
    rateLimit,
    ingestDocumentController
);

export default router;